export declare const map: AMap.Map;
export declare const lnglat: AMap.LngLat;
export declare const size: AMap.Size;
export declare const lnglatTuple: [number, number];
export declare const pixel: AMap.Pixel;
export declare const marker: AMap.Marker;
export declare const circle: AMap.Circle;
export declare const markerShape: AMap.MarkerShape;
export declare const icon: AMap.Icon;
export declare const bounds: AMap.Bounds;
export declare const div: HTMLDivElement;
export declare const polygon: AMap.Polygon;
export declare const lang: AMap.Lang;
